from tkinter import  *
top=Tk()
top.title('注册界面')
label1=Label(top,text='用户名')
label2=Label(top,text='密码')
label3=Label(top,text='电子邮件')
label4=Label(top,text='手机号')
text1=Entry(top)
text2=Entry(top,show='*')
text3=Entry(top)
text4=Entry(top)
label_final=Label(top)
def judge():
    s1=text1.get()
    s2=text2.get()
    s3=text3.get()
    s4=text4.get()
    if(s1=='1' or s2=='' or s3=='' or s4==''):
        label_final1=Label(top,text='有项目未填写',bg='red')
        label_final1.grid_configure(row=5,column=2,sticky=S)
    else:
        print('新注册了一个用户')
        print('用户名是：',text1.get())
        print('密码是：',text2.get())
        print('电子邮件地址是：',text3.get())
        print('手机号是：',text4.get())
button1=Button(top,text='提交',command=judge)
label1.grid_configure(row=1,column=1)
label2.grid_configure(row=2,column=1)
label3.grid_configure(row=3,column=1)
label4.grid_configure(row=4,column=1)
text1.grid_configure(row=1,column=2,sticky = W)
text2.grid_configure(row=2,column=2,sticky = W)
text3.grid_configure(row=3,column=2,sticky = W)
text4.grid_configure(row=4,column=2,sticky = W)
label_final.grid_configure(row=5)
button1.grid_configure(row=6,column=2,sticky=S)
top.mainloop()
